### ISSUE TITLE
MSF avec ORB SLAM et IMU

### ISSUE THREAD

**Issue by eterriault** [evter95/ethzasl_msf#14]
Pendant les vacances de Noël
https://pixhawk.org/dev/ros/visual_estimation

**Comment by eterriault** [comment]
MSF roule, mais on n'a pas eu le temps de tester les données qui en sortent.

[--- Commented from Asana.com
#commenter Eva Terriault
---[aa]

**Comment by eterriault** [comment]
Update #2: MSF donne des donnes qui ont du sens, mais il reste à voir à quel point ils sont exacts

[--- Commented from Asana.com
#commenter Eva Terriault
---[aa]

**Comment by eterriault** [comment]
Update #3: Les données semblent être relativement bien scalés, et assez fiables. Il reste à résoudre le problème des axes : https://github.com/evter95/ethzasl_msf/issues/4

[--- Commented from Asana.com
#commenter Eva Terriault
---[aa]

**Comment by eterriault** [comment]
Update #4: Pas très concluant aujourd'hui... Quelques déouvertes/hypothèses:
1. MSF s'initilalise dans un référentiel qui n'est pas celui du monde (aucun axe n'est parfaitement haut/bas, gauche/droite ou avant/arrière). C'est en partie pour ça que les données de rqt_plot étaient un peu pas claires.
2. J'ai l'impression (need more testing) que msf_core/pose/pose/pose/position donne une accélération (fait pas trop de sens, mais bon). Un mouvement brusque va faire monter puis redescendre les données.
3. En faisant des plus larges mouvements (marcher dans le laboratoire) ORB se perd desfois, et n'est plus capable de se réinitialiser. Il faudrait mettre un time_out dans le code pour lancer la réinitialisation après X temps mort.
4. J'ai ajouté ce plugin à rviz pour pouvoir visualier une PoseWithCovariance : https://github.com/laas/rviz_plugin_covariance
5. #4 m'a permis de voir que l'orientation (pas la position) donnée par MSF est assez fiable.

Issues GitHub à venir

[--- Commented from Asana.com
#commenter Eva Terriault
---[aa]

**Comment by unito-tester** [comment]
Vraiment intéressant!

[--- Commented from Asana.com
#commenter Alexandre Borowczyk
---[aa]

**Comment by unito-tester** [comment]
J'ai plonge un peut dans orb_slam et sa a soulever des interrogations
Question : 
- Est-ce qu'on avais mis les données de calibration de la camera dans le fichier https://github.com/AlexandreBorowczyk/ORB_SLAM/blob/master/Data/Settings.yaml pour ORB_Slam?

[--- Commented from Asana.com
#commenter Alexandre Borowczyk
---[aa]

**Comment by unito-tester** [comment]
Oui. Ecq c'est ça qu'il faut ? Je peux t'envoyer le fichier si tu veux

[--- Commented from Asana.com
#commenter Eva Terriault
---[aa]
