### ISSUE TITLE
Inertial Navigation

### ISSUE THREAD

**Issue by eterriault** [evter95/ethzasl_msf#16]
http://www.vectornav.com/support/library/imu-and-ins

**Comment by eterriault** [comment]
Parlant de VectorNav, est-ce que leurs produits sont bons?

[--- Commented from Asana.com
#commenter Andre Phu-Van Nguyen
---[aa]

**Comment by eterriault** [comment]
Si je ne me trompe pas je pense que l'agence spatiale canadienne à mis de leur IMU sur leur rover a St-Brunos

[--- Commented from Asana.com
#commenter Alexandre Borowczyk
---[aa]

**Comment by eterriault** [comment]
OK nice , jetais entrain de les checker pour demander un vn-100 en commandite

[--- Commented from Asana.com
#commenter Andre Phu-Van Nguyen
---[aa]

**Comment by eterriault** [comment]
Nice! Disons que si on était oronos et on commandait sa, la Grc viendrais nous rendre visite.

[--- Commented from Asana.com
#commenter Alexandre Borowczyk
---[aa]

**Comment by unito-tester** [comment]
Navigation Inertielle expliquée du point de vue d'un manufacturier de centrales inertielles.

[--- Commented from Asana.com
#commenter Alexandre Borowczyk
---[aa]
