### ISSUE TITLE
Lukas-Kanade optical flow

### ISSUE THREAD

**Issue by eterriault** [evter95/ethzasl_msf#9]

**Comment by unito-tester** [comment]
Pourquoi refaire du optical flow?

[--- Commented from Asana.com
#commenter Andre Phu-Van Nguyen
---[aa]

**Comment by unito-tester** [comment]
Why not?

[--- Commented from Asana.com
#commenter Antonio Sanniravong
---[aa]

**Comment by unito-tester** [comment]
Ben je sais pas ce que tu veux dire par refaire, on l'a jamais fait, mais jai juste poster des suggestions vraiment vagues ici a un moment donne pour brainstorm. Tu peux enlever ou ajouter ce que tu veux.

[--- Commented from Asana.com
#commenter Antonio Sanniravong
---[aa]

**Comment by unito-tester** [comment]
Ben c pas ce que le px4flow fait?

[--- Commented from Asana.com
#commenter Andre Phu-Van Nguyen
---[aa]

**Comment by unito-tester** [comment]
Ahh ok ok, ben je me disais qu'avec OpenCV avec du feature detection et un FOV plus wide pourrait servir de complément au px4flow.

[--- Commented from Asana.com
#commenter Antonio Sanniravong
---[aa]

**Comment by unito-tester** [comment]
Ah mais tu sais que ils ont implémenté klt sur le px4flow et que tu peux changer la lentille et configurer un paramètre?

[--- Commented from Asana.com
#commenter Andre Phu-Van Nguyen
---[aa]

**Comment by unito-tester** [comment]
(Pour set le focal length)

[--- Commented from Asana.com
#commenter Andre Phu-Van Nguyen
---[aa]

**Comment by unito-tester** [comment]
Ow, je savais pas ça. Ok je viens de voir les branches KLT. Mais elles sont 100+ commits behind, c'est tu legit?

[--- Commented from Asana.com
#commenter Antonio Sanniravong
---[aa]

**Comment by unito-tester** [comment]
https://groups.google.com/d/msg/px4users/g5lcrYMV4DU/zD7jLKOyEgAJ

Apparently?

[--- Commented from Asana.com
#commenter Andre Phu-Van Nguyen
---[aa]

**Comment by unito-tester** [comment]
Yo apparemment que le firmware KLT est genre moins bon que le patch based search hahaha

[--- Commented from Asana.com
#commenter Andre Phu-Van Nguyen
---[aa]
